### ISSUE TITLE
truncated octahedron PBC

### ISSUE THREAD

**Issue by jayponder** [zhi-wang/tinker.gpu#84]

**Comment by zhi-wang** [comment]
Tinker vriable `octahedron` was used in:
   - [ ] analyze.f: to print box info
   - [x] bounds.f
   - [ ] boxes.f
   - [ ] echarge*.f: recip
   - [ ] edisp*.f: recip
   - [ ] empole*.f: recip
   - [ ] epolar*.f: recip
   - [x] image.f: PBC
   - [ ] lattice.f
   - [ ] lights.f
   - [x] nblist.f
   - [ ] polymer.f
   - [ ] radial.f
   - [ ] replica.f
   - [ ] testvir.f
   - [ ] unitcell.f

I will check the box if I had put similar code here.
